/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Database.KoneksiDB;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author User
 */
public class FormUtama extends javax.swing.JFrame {

private KoneksiDB con;
private Statement st;
private ResultSet rs;
private String sql="";
String hakakses;
    /**
     * Creates new form FormUtama
     */
    public FormUtama() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        setMenuLogout();
    }
    
    void setMenuLoginAdmin(){
        transaksi.setEnabled(true);
        karyawan.setEnabled(true);
        barang.setEnabled(true);
        laporan.setEnabled(true);
        
    }
    
    void setMenuLoginKaryawan(){
        transaksi.setEnabled(true);
        karyawan.setEnabled(false);
        barang.setEnabled(false);
        laporan.setEnabled(false);
    }
    
    private void setMenuLogout(){
            transaksi.setEnabled(false);
            karyawan.setEnabled(false);
            barang.setEnabled(false);
            laporan.setEnabled(false);
            file.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpMenuUtama = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        login = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        keluar = new javax.swing.JMenuItem();
        transaksi = new javax.swing.JMenu();
        mnKasir = new javax.swing.JMenuItem();
        karyawan = new javax.swing.JMenu();
        mnKaryawan = new javax.swing.JMenuItem();
        barang = new javax.swing.JMenu();
        mnBarang = new javax.swing.JMenuItem();
        laporan = new javax.swing.JMenu();
        LapPenjualan = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Utama");

        javax.swing.GroupLayout dpMenuUtamaLayout = new javax.swing.GroupLayout(dpMenuUtama);
        dpMenuUtama.setLayout(dpMenuUtamaLayout);
        dpMenuUtamaLayout.setHorizontalGroup(
            dpMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        dpMenuUtamaLayout.setVerticalGroup(
            dpMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 347, Short.MAX_VALUE)
        );

        file.setText("File");

        login.setText("Log In");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        file.add(login);

        logout.setText("Log Out");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        file.add(logout);
        file.add(jSeparator1);

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        file.add(keluar);

        jMenuBar1.add(file);

        transaksi.setText("Transaksi");

        mnKasir.setText("Kasir");
        mnKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKasirActionPerformed(evt);
            }
        });
        transaksi.add(mnKasir);

        jMenuBar1.add(transaksi);

        karyawan.setText("Karyawan");

        mnKaryawan.setText("Data Karyawan");
        mnKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKaryawanActionPerformed(evt);
            }
        });
        karyawan.add(mnKaryawan);

        jMenuBar1.add(karyawan);

        barang.setText("Barang");

        mnBarang.setText("Data Barang");
        mnBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBarangActionPerformed(evt);
            }
        });
        barang.add(mnBarang);

        jMenuBar1.add(barang);

        laporan.setText("Laporan");

        LapPenjualan.setText("Laporan Penjualan");
        LapPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LapPenjualanActionPerformed(evt);
            }
        });
        laporan.add(LapPenjualan);

        jMenuBar1.add(laporan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpMenuUtama)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpMenuUtama)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        setMenuLogout();
    }//GEN-LAST:event_logoutActionPerformed

    private void mnKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKaryawanActionPerformed
        dpMenuUtama.removeAll();
        dpMenuUtama.updateUI();
        FormKaryawan karyawan = new FormKaryawan();
        dpMenuUtama.add(karyawan);
        karyawan.setVisible(true);
    }//GEN-LAST:event_mnKaryawanActionPerformed

    private void mnBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBarangActionPerformed
        dpMenuUtama.removeAll();
        dpMenuUtama.updateUI();
        FormBarang barang = new FormBarang();
        dpMenuUtama.add(barang);
        barang.setVisible(true);
    }//GEN-LAST:event_mnBarangActionPerformed

    private void LapPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LapPenjualanActionPerformed
        dpMenuUtama.removeAll();
        dpMenuUtama.updateUI();
        FormDetailTransaksi detail = new FormDetailTransaksi();
        dpMenuUtama.add(detail);
        detail.setVisible(true);
    }//GEN-LAST:event_LapPenjualanActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        FormLogin login = new FormLogin();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_loginActionPerformed

    private void mnKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKasirActionPerformed
        dpMenuUtama.removeAll();
        dpMenuUtama.updateUI();
        FormKasir penjualan = new FormKasir();
        dpMenuUtama.add(penjualan);
        penjualan.setVisible(true);
    }//GEN-LAST:event_mnKasirActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        dispose();
    }//GEN-LAST:event_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem LapPenjualan;
    private javax.swing.JMenu barang;
    private javax.swing.JDesktopPane dpMenuUtama;
    private javax.swing.JMenu file;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu karyawan;
    private javax.swing.JMenuItem keluar;
    private javax.swing.JMenu laporan;
    private javax.swing.JMenuItem login;
    private javax.swing.JMenuItem logout;
    private javax.swing.JMenuItem mnBarang;
    private javax.swing.JMenuItem mnKaryawan;
    private javax.swing.JMenuItem mnKasir;
    private javax.swing.JMenu transaksi;
    // End of variables declaration//GEN-END:variables
}
